# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - "thesuavehog"
    assignees:
      - "thesauvehog"
    commit-message:
      prefix: "fix: "
    groups:
      patches:
        applies-to: version-updates
        update-types:
          - "patch"
      aws-sdk:
        applies-to: version-updates
        patterns:
          - "@aws-sdk/*"
          - "aws-cdk*"
          - "cdk"
          - "constructs"
        update-types:
          - "minor"
