docs:
  - changed-files:
    - any-glob-to-any-file:
      - docs/**
      - "**/*.md"

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - package-lock.json
      - yarn.lock

ci:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**
